server:
  port: 23001

eureka:
  instance:
    hostname: localhost
    #prefer-ip-address true 表示服务注册时，使用ip地址 而不是hostname
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
